### ISSUE TITLE
Finalize documentation

### ISSUE THREAD

**Issue by mr-devs** [mr-devs/top-FIBers#37]
I am adding all of us but likely I will handle most of this myself.

### ToDo List
The below is for when the repo is ready and all data has been updated.

- [x] Make sure that the README docs are correct in all directories
- [x] Update the web-based documentation (see [this](https://www.matthewdeverna.com/top-FIBers/)) which is quite outdated at this point.
    - [ ] Nice to have: Can we create a diagram of the infrastructure and the data processing pipeline? (use https://app.diagrams.net/)

**Comment by mr-devs** [comment]
Completed
